using SubDataUpload.Config;
using SubDataUpload.DataFormat;
using SubDataUpload.Storage;
using System.Collections.Generic;


namespace SubDataUpload
{
    // Start time for all subs 8:45
    // Completion Time : 10:59
    // Total run time : ~02:15:00

    /// <summary>
    /// Point this program to the directory that contains the child directories 
    /// that were generated by the SubscripionOverview.ps1 file. It grabs all of 
    /// the output files and uploads them to the specified Azure Storage Account
    /// in the configuration file.
    /// 
    /// This can be done by using another PS1 script to call the SubscriptionOverview.ps1
    /// multiple times creating a series of directories with content. 
    /// 
    /// The data there will be used to feed a dashboard of some sort. 
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            Configuration config = Configuration.LoadConfiguration();
            List<SubscriptionData> subData = config.CollectSubscriptionInformation();
            AzureStorage storageUtility = new AzureStorage(config);
            bool result = storageUtility.UploadLatestData(subData).Result;
        }
    }
}
